//HintName: GeneratedPromptExtensions.g.cs
// <auto-generated/>
#nullable enable

namespace EnterpriseLangfuse.Prompts;

/// <summary>
/// Strongly typed accessors generated from this project's <c>.prompt.yaml</c> files.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("EnterpriseLangfuse.Generators", null)]
public static class GeneratedPromptExtensions
{
    /// <summary>
    /// Resolves the <c>Static</c> prompt and compiles it with the supplied variables.
    /// </summary>
    /// <param name="provider">The provider to resolve through.</param>
    /// <param name="label">The Langfuse label to resolve, e.g. <c>production</c>.</param>
    /// <param name="cancellationToken">Cancels the fetch.</param>
    /// <returns>The prompt with every variable substituted.</returns>
    public static async global::System.Threading.Tasks.Task<global::EnterpriseLangfuse.Prompts.CompiledPrompt> GetStaticPromptAsync(
        this global::EnterpriseLangfuse.Prompts.IPromptProvider provider,
        string label = global::EnterpriseLangfuse.Prompts.LangfuseDefaults.ProductionLabel,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        var variables = new global::System.Collections.Generic.Dictionary<string, object?>(0, global::System.StringComparer.Ordinal);

        var prompt = await provider.GetPromptAsync(@"Static", label, cancellationToken).ConfigureAwait(false);
        return prompt.Compile(variables);
    }
}
