//HintName: GeneratedPromptExtensions.g.cs
// <auto-generated/>
#nullable enable

namespace EnterpriseLangfuse.Prompts;

/// <summary>
/// Strongly typed accessors generated from this project's <c>.prompt.yaml</c> files.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("EnterpriseLangfuse.Generators", null)]
public static class GeneratedPromptExtensions
{
    /// <summary>
    /// Resolves the <c>RefundAgent</c> prompt and compiles it with the supplied variables.
    /// </summary>
    /// <param name="provider">The provider to resolve through.</param>
    /// <param name="customerName">Bound to the <c>{{customerName}}</c> template variable.</param>
    /// <param name="orderId">Bound to the <c>{{orderId}}</c> template variable.</param>
    /// <param name="label">The Langfuse label to resolve, e.g. <c>production</c>.</param>
    /// <param name="cancellationToken">Cancels the fetch.</param>
    /// <returns>The prompt with every variable substituted.</returns>
    public static async global::System.Threading.Tasks.Task<global::EnterpriseLangfuse.Prompts.CompiledPrompt> GetRefundAgentPromptAsync(
        this global::EnterpriseLangfuse.Prompts.IPromptProvider provider,
        string customerName,
        string orderId,
        string label = global::EnterpriseLangfuse.Prompts.LangfuseDefaults.ProductionLabel,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        var variables = new global::System.Collections.Generic.Dictionary<string, object?>(2, global::System.StringComparer.Ordinal)
        {
            [@"customerName"] = customerName,
            [@"orderId"] = orderId,
        };

        var prompt = await provider.GetPromptAsync(@"RefundAgent", label, cancellationToken).ConfigureAwait(false);
        return prompt.Compile(variables);
    }
}
