//HintName: GeneratedPromptExtensions.g.cs
// <auto-generated/>
#nullable enable

namespace EnterpriseLangfuse.Prompts;

/// <summary>
/// Strongly typed accessors generated from this project's <c>.prompt.yaml</c> files.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("EnterpriseLangfuse.Generators", null)]
public static class GeneratedPromptExtensions
{
    /// <summary>
    /// Resolves the <c>support triage.v2</c> prompt and compiles it with the supplied variables.
    /// </summary>
    /// <param name="provider">The provider to resolve through.</param>
    /// <param name="class">Bound to the <c>{{class}}</c> template variable.</param>
    /// <param name="label2">Bound to the <c>{{label}}</c> template variable.</param>
    /// <param name="customer_tier">Bound to the <c>{{customer_tier}}</c> template variable.</param>
    /// <param name="label">The Langfuse label to resolve, e.g. <c>production</c>.</param>
    /// <param name="cancellationToken">Cancels the fetch.</param>
    /// <returns>The prompt with every variable substituted.</returns>
    public static async global::System.Threading.Tasks.Task<global::EnterpriseLangfuse.Prompts.CompiledPrompt> GetSupportTriageV2PromptAsync(
        this global::EnterpriseLangfuse.Prompts.IPromptProvider provider,
        string @class,
        string label2,
        string customer_tier,
        string label = global::EnterpriseLangfuse.Prompts.LangfuseDefaults.ProductionLabel,
        global::System.Threading.CancellationToken cancellationToken = default)
    {
        var variables = new global::System.Collections.Generic.Dictionary<string, object?>(3, global::System.StringComparer.Ordinal)
        {
            [@"class"] = @class,
            [@"label"] = label2,
            [@"customer_tier"] = customer_tier,
        };

        var prompt = await provider.GetPromptAsync(@"support triage.v2", label, cancellationToken).ConfigureAwait(false);
        return prompt.Compile(variables);
    }
}
