using System.Collections.Generic;
using System.Text;

namespace EnterpriseLangfuse.Generators;

/// <summary>Renders the parsed prompt models into the extension-method source text.</summary>
internal static class PromptSourceEmitter
{
    /// <summary>The namespace the extensions land in — the same one <c>IPromptProvider</c> lives in.</summary>
    /// <remarks>
    /// Emitting alongside the interface means anyone who can name <c>IPromptProvider</c> already has
    /// these methods in scope, with no extra using directive to discover.
    /// </remarks>
    private const string Namespace = "EnterpriseLangfuse.Prompts";

    private const string ClassName = "GeneratedPromptExtensions";

    /// <summary>The file name handed to <c>AddSource</c>.</summary>
    public const string HintName = "GeneratedPromptExtensions.g.cs";

    public static string Emit(IReadOnlyList<PromptModel> prompts)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {Namespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Strongly typed accessors generated from this project's <c>.prompt.yaml</c> files.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"EnterpriseLangfuse.Generators\", null)]");
        builder.AppendLine($"public static class {ClassName}");
        builder.AppendLine("{");

        for (var i = 0; i < prompts.Count; i++)
        {
            if (i > 0)
            {
                builder.AppendLine();
            }

            EmitMethod(builder, prompts[i]);
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void EmitMethod(StringBuilder builder, PromptModel prompt)
    {
        builder.AppendLine("    /// <summary>");
        builder.AppendLine($"    /// Resolves the <c>{Xml(prompt.PromptName)}</c> prompt and compiles it with the supplied variables.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <param name=\"provider\">The provider to resolve through.</param>");

        foreach (var variable in prompt.Variables)
        {
            builder.AppendLine(
                $"    /// <param name=\"{Xml(Unescape(variable.ParameterName))}\">Bound to the <c>{{{{{Xml(variable.TemplateName)}}}}}</c> template variable.</param>");
        }

        builder.AppendLine("    /// <param name=\"label\">The Langfuse label to resolve, e.g. <c>production</c>.</param>");
        builder.AppendLine("    /// <param name=\"cancellationToken\">Cancels the fetch.</param>");
        builder.AppendLine("    /// <returns>The prompt with every variable substituted.</returns>");

        builder.AppendLine(
            $"    public static async global::System.Threading.Tasks.Task<global::{Namespace}.CompiledPrompt> {prompt.MethodName}(");
        builder.AppendLine($"        this global::{Namespace}.IPromptProvider provider,");

        foreach (var variable in prompt.Variables)
        {
            builder.AppendLine($"        string {variable.ParameterName},");
        }

        // Defaulted from the runtime constant so the generated default can never drift from the interface's.
        builder.AppendLine($"        string label = global::{Namespace}.LangfuseDefaults.ProductionLabel,");
        builder.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");

        var dictionary =
            $"new global::System.Collections.Generic.Dictionary<string, object?>({prompt.Variables.Count}, global::System.StringComparer.Ordinal)";

        if (prompt.Variables.Count == 0)
        {
            builder.AppendLine($"        var variables = {dictionary};");
        }
        else
        {
            builder.AppendLine($"        var variables = {dictionary}");
            builder.AppendLine("        {");

            foreach (var variable in prompt.Variables)
            {
                builder.AppendLine($"            [{Literal(variable.TemplateName)}] = {variable.ParameterName},");
            }

            builder.AppendLine("        };");
        }

        builder.AppendLine();
        builder.AppendLine(
            $"        var prompt = await provider.GetPromptAsync({Literal(prompt.PromptName)}, label, cancellationToken).ConfigureAwait(false);");
        builder.AppendLine("        return prompt.Compile(variables);");
        builder.AppendLine("    }");
    }

    /// <summary>Emits a verbatim string literal; prompt names are data and may contain anything.</summary>
    private static string Literal(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";

    /// <summary>Escapes a value for interpolation into a <c>///</c> documentation comment.</summary>
    private static string Xml(string value)
    {
        var builder = new StringBuilder(value.Length);

        foreach (var character in value)
        {
            switch (character)
            {
                case '&':
                    builder.Append("&amp;");
                    break;
                case '<':
                    builder.Append("&lt;");
                    break;
                case '>':
                    builder.Append("&gt;");
                    break;
                default:
                    // A doc comment only reaches to the end of its line: a control character — the
                    // newline of a YAML block-scalar name, say — would terminate the comment and
                    // drop the rest of the value into the generated file as raw code.
                    builder.Append(char.IsControl(character) ? ' ' : character);
                    break;
            }
        }

        return builder.ToString();
    }

    /// <summary>A <c>&lt;param&gt;</c> tag names the parameter without the keyword-escaping <c>@</c>.</summary>
    private static string Unescape(string parameterName) =>
        parameterName.StartsWith("@", System.StringComparison.Ordinal) ? parameterName.Substring(1) : parameterName;
}
