namespace EnterpriseLangfuse.Prompts;

/// <summary>Base type for every error this framework raises, so callers can catch one type.</summary>
public abstract class EnterpriseLangfuseException : Exception
{
    /// <param name="message">The error message.</param>
    protected EnterpriseLangfuseException(string message)
        : base(message)
    {
    }

    /// <param name="message">The error message.</param>
    /// <param name="innerException">The underlying cause, if any.</param>
    protected EnterpriseLangfuseException(string message, Exception? innerException)
        : base(message, innerException)
    {
    }
}

/// <summary>
/// Thrown when a prompt could not be served from Langfuse <em>or</em> from an embedded fallback.
/// </summary>
/// <remarks>
/// This is the genuinely unrecoverable case: the network failed and no local copy of the prompt was
/// compiled into the application. It is kept distinct from a transport failure so that callers can
/// tell "Langfuse is down but we served a fallback" (no exception) from "we have nothing to serve".
/// </remarks>
public sealed class PromptNotFoundException : EnterpriseLangfuseException
{
    /// <param name="promptName">The prompt that could not be resolved.</param>
    /// <param name="label">The label that was requested, if any.</param>
    /// <param name="innerException">The transport or API failure that prevented resolution.</param>
    public PromptNotFoundException(string promptName, string? label, Exception? innerException = null)
        : base(
            $"Prompt '{promptName}'{(label is null ? string.Empty : $" with label '{label}'")} could not be resolved " +
            "from Langfuse, and no embedded fallback was found. Add the prompt as an EmbeddedResource " +
            "(*.prompt.yaml) to guarantee availability during an outage.",
            innerException)
    {
        PromptName = promptName;
        Label = label;
    }

    /// <summary>The prompt that could not be resolved.</summary>
    public string PromptName { get; }

    /// <summary>The label that was requested, if any.</summary>
    public string? Label { get; }
}

/// <summary>
/// Thrown when compiling a prompt whose template references a variable the caller did not supply.
/// </summary>
/// <remarks>
/// Code generated by EnterpriseLangfuse.Generators makes this unreachable — the compiler enforces the
/// variable list. It remains reachable for callers who compile with a hand-built dictionary.
/// </remarks>
public sealed class MissingPromptVariableException : EnterpriseLangfuseException
{
    /// <param name="promptName">The prompt being compiled.</param>
    /// <param name="variableName">The variable that had no value supplied.</param>
    public MissingPromptVariableException(string promptName, string variableName)
        : base($"Prompt '{promptName}' references variable '{{{{{variableName}}}}}', but no value was supplied.")
    {
        PromptName = promptName;
        VariableName = variableName;
    }

    /// <summary>The prompt being compiled.</summary>
    public string PromptName { get; }

    /// <summary>The variable that had no value supplied.</summary>
    public string VariableName { get; }
}

/// <summary>Thrown when the Langfuse API returns a response this framework cannot interpret.</summary>
public sealed class LangfuseApiException : EnterpriseLangfuseException
{
    /// <param name="message">The error message.</param>
    /// <param name="statusCode">The HTTP status Langfuse responded with, if the call reached it.</param>
    /// <param name="innerException">The underlying parse or transport failure.</param>
    public LangfuseApiException(string message, System.Net.HttpStatusCode? statusCode = null, Exception? innerException = null)
        : base(message, innerException)
    {
        StatusCode = statusCode;
    }

    /// <summary>The HTTP status Langfuse responded with, if the call reached it.</summary>
    public System.Net.HttpStatusCode? StatusCode { get; }
}
